name: build

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    env:
      FOLDER: "tplink_tl-wr1043nd"
      FILE_NAME: "tl-wr1043nd-webflash.bin"
      TPLINK_NAME: "wr1043nv1_en_3_13_15_up_boot(140319).bin"
      TFTP_NAME: "wr1043nv1_tp_recovery.bin"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build CRCALC
        run: |
          svn co https://github.com/mirror/firmware-mod-kit/trunk/src/crcalc
          (cd crcalc && make && sudo cp crcalc /usr/local/bin)

      - name: Download firmware
        run: |
          BASE_URL="ftp://ftp.dd-wrt.com/betas/$(date +'%Y')"
          LAST=$(curl -l "$BASE_URL/" | tail -1)
          curl "$BASE_URL/$LAST/$FOLDER/$FILE_NAME" -o "$FILE_NAME"

      # 44442D575254 -> DD-WRT
      - name: Fix Header Vendor
        run: echo 0:44442D57525400000000000000000000 | xxd -r | dd of="$FILE_NAME" conv=notrunc bs=1 seek=$((0x20))

      # 3234 -> 24
      - name: Fix Header Version
        run: echo 0:00000000000000003234000000000000 | xxd -r | dd of="$FILE_NAME" conv=notrunc bs=1 seek=$((0x30))

      - name: Fix Checksum
        run: crcalc "$FILE_NAME"

      - name: Upload webflash
        uses: actions/upload-artifact@v1
        with:
          name: ${{ env.FILE_NAME }}
          path: ${{ env.FILE_NAME }}

      - name: Generate factory to DD-WRT version
        run: dd if="$FILE_NAME" of="factory-to-ddwrt.bin" bs=1 skip=28

      - name: Upload factory
        uses: actions/upload-artifact@v1
        with:
          name: "factory-to-ddwrt.bin"
          path: "factory-to-ddwrt.bin"

      - name: Generate TFTP recovery version
        run: |
          dd if="tplink_firmware/$TPLINK_NAME" of=begin_firmware.bin bs=512 count=257
          dd if="tplink_firmware/$TPLINK_NAME" of=end_firmware.bin   bs=512 skip=16001
          cat begin_firmware.bin    > $TFTP_NAME
          cat factory-to-ddwrt.bin >> $TFTP_NAME
          cat end_firmware.bin     >> $TFTP_NAME

      - name: Upload TFTP recovery
        uses: actions/upload-artifact@v1
        with:
          name: ${{ env.TFTP_NAME }}
          path: ${{ env.TFTP_NAME }}
