name: release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    env:
      FOLDER: "tplink_tl-wr1043nd"
      FILE_NAME: "tl-wr1043nd-webflash.bin"
      TPLINK_NAME: "wr1043nv1_en_3_13_15_up_boot(140319).bin"
      TFTP_NAME: "wr1043nv1_tp_recovery.bin"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build CRCALC
        run: |
          svn co https://github.com/mirror/firmware-mod-kit/trunk/src/crcalc
          (cd crcalc && make && sudo cp crcalc /usr/local/bin)

      - name: Download firmware
        run: |
          VERSION="${GITHUB_REF/refs\/tags\//}"
          echo "::set-env name=VERSION::$VERSION"
          YEAR="${VERSION:6:4}"
          echo "::set-env name=YEAR::$YEAR"
          curl "ftp://ftp.dd-wrt.com/betas/$YEAR/$VERSION/$FOLDER/$FILE_NAME" -o "$FILE_NAME"

      # 44442D575254 -> DD-WRT
      - name: Fix Header Vendor
        run: echo 0:44442D57525400000000000000000000 | xxd -r | dd of="$FILE_NAME" conv=notrunc bs=1 seek=$((0x20))

      # 3234 -> 24
      - name: Fix Header Version
        run: echo 0:00000000000000003234000000000000 | xxd -r | dd of="$FILE_NAME" conv=notrunc bs=1 seek=$((0x30))

      - name: Fix Checksum
        run: crcalc "$FILE_NAME"

      - name: Generate factory to DD-WRT version
        run: dd if="$FILE_NAME" of="factory-to-ddwrt.bin" bs=1 skip=28

      - name: Generate TFTP recovery version
        run: |
          dd if="tplink_firmware/$TPLINK_NAME" of=begin_firmware.bin bs=512 count=257
          dd if="tplink_firmware/$TPLINK_NAME" of=end_firmware.bin   bs=512 skip=16001
          cat begin_firmware.bin    > $TFTP_NAME
          cat factory-to-ddwrt.bin >> $TFTP_NAME
          cat end_firmware.bin     >> $TFTP_NAME

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: ${{ env.VERSION }}
          body: |
            ## ${{ env.VERSION }} ![GitHub Releases](https://img.shields.io/github/downloads/${{ github.repository }}/${{ env.VERSION }}/total)
            DD-WRT firmwares for WR1043ND V1
            * [factory-to-ddwrt.bin](https://github.com/${{ github.repository }}/releases/download/${{ env.VERSION }}/factory-to-ddwrt.bin): from TP-LINK to DD-WRT
            * [${{ env.FILE_NAME }}](https://github.com/${{ github.repository }}/releases/download/${{ env.VERSION }}/${{ env.FILE_NAME }}): DD-WRT upgrade
            * [${{ env.TFTP_NAME }}](https://github.com/${{ github.repository }}/releases/download/${{ env.VERSION }}/${{ env.TFTP_NAME }}): TTFT Recovery

            Source: https://download1.dd-wrt.com/dd-wrtv2/downloads/betas/${{ env.YEAR }}/${{ env.VERSION }}/${{ env.FOLDER }}/
          draft: false
          prerelease: false

      - name: Upload factory to ddwrt
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: factory-to-ddwrt.bin
          asset_name: factory-to-ddwrt.bin
          asset_content_type: application/octet-stream

      - name: Upload webflash
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.FILE_NAME }}
          asset_name: ${{ env.FILE_NAME }}
          asset_content_type: application/octet-stream

      - name: Upload TFTP recovery
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.TFTP_NAME }}
          asset_name: ${{ env.TFTP_NAME }}
          asset_content_type: application/octet-stream
